### ISSUE TITLE
[security]XSS in "New folder" option

### ISSUE THREAD

**Issue by fikaav73** [alexantr/filemanager#20]
You can write anything, like 

> `<h1>asd</h1>`

 it will totally mess up the page.
Iframes also work, and everything you can imagine.

**Comment by LE0ZY** [comment]
I suggest he put `htmlspecialchars(...)`

**Comment by alexantr** [comment]
Can't reproduce bug. Function `strip_tags` applies while creating folder and `htmlspecialchars` in list.

**Comment by AndNovAtor** [comment]
For the history: This bug was on old version, before commit 2f05d7e5759b3171b6c82c965e9cad9e6f7fa3d1 (7 Dec 2017). I also had old version before this commit and I reproduced this "bug" (after open this issue). After adding strip_tags and htmlspecialchars in the commit (7 Dec 2017) this bug does not occur. So, as this issue was on 16 Aug 2017, this issue can be marked as resolved - the issue can be closed, @alexantr .
Sorry for necroposting ><

**Comment by attritionorg** [comment]
Did this allow for JavaScript injection? The PoC in the original post was only for HTML injection.
